name: GO-APP CI

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
        DOCKERHUB_USERNAME:
            required: true
        DOCKERHUB_TOKEN:
            required: true

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Change Directory
        run: cd ./GO-APP || ls -la

      - name: docker build
        run: docker build --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}:${{ inputs.tag }}

      - name: push image to docker hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ inputs.tag }}