name: GO-APP CI

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
        DOCKERHUB_USERNAME:
            required: true
        DOCKERHUB_TOKEN:
            required: true

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.25'
      
      - name: Get in Folder
        run: cd ./GO-APP

      - name: Install dependencies
        run: go mod tidy

      - name: Build project
        run: go build -o server .
        working-directory: ./GO-APP

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
            context: .
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}:${{ inputs.tag }}