name: GO-APP CI

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
        DOCKERHUB_USERNAME:
            required: true
        DOCKERHUB_TOKEN:
            required: true

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: docker build
        run: docker build -f ./GO-APP -t ${{ secrets.DOCKERHUB_USERNAME }}:${{ inputs.tag }}

      - name: push image to docker hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ inputs.tag }}